"""agent forge baseline

Revision ID: 0001_agent_forge_baseline
Revises:
Create Date: 2026-06-08 14:51:19.066077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001_agent_forge_baseline'
down_revision: Union[str, Sequence[str], None] = '32e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "agents" in inspector.get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_release_snapshots',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_spec_json', sa.Text(), nullable=False),
    sa.Column('runtime_spec_json', sa.Text(), nullable=False),
    sa.Column('runtime_manifest_json', sa.Text(), nullable=False),
    sa.Column('spec_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manifest_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("status = 'published'", name='ck_agent_release_snapshots_status_published'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_release_snapshots_agent_version')
    )
    op.create_index(op.f('ix_agent_release_snapshots_agent_id'), 'agent_release_snapshots', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_release_snapshots_manifest_hash'), 'agent_release_snapshots', ['manifest_hash'], unique=False)
    op.create_index(op.f('ix_agent_release_snapshots_org_id'), 'agent_release_snapshots', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_release_snapshots_spec_hash'), 'agent_release_snapshots', ['spec_hash'], unique=False)
    op.create_index(op.f('ix_agent_release_snapshots_version'), 'agent_release_snapshots', ['version'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rerun_of_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_version', sa.Integer(), nullable=False),
    sa.Column('spec_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('runtime_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entrypoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tools_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('first_token_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('subagents_json', sa.Text(), nullable=False),
    sa.Column('runtime_spec_json', sa.Text(), nullable=False),
    sa.Column('runtime_manifest_json', sa.Text(), nullable=False),
    sa.Column('knowledge_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_entrypoint'), 'agent_runs', ['entrypoint'], unique=False)
    op.create_index(op.f('ix_agent_runs_org_id'), 'agent_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_release_id'), 'agent_runs', ['release_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_rerun_of_run_id'), 'agent_runs', ['rerun_of_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_source'), 'agent_runs', ['run_source'], unique=False)
    op.create_index(op.f('ix_agent_runs_runtime_source'), 'agent_runs', ['runtime_source'], unique=False)
    op.create_index(op.f('ix_agent_runs_spec_hash'), 'agent_runs', ['spec_hash'], unique=False)
    op.create_index('ix_agent_runs_total_tokens', 'agent_runs', ['total_tokens'], unique=False)
    op.create_table('agent_test_cases',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_keywords_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assertion_json', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_runtime_plan_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_run_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_test_cases_agent_id'), 'agent_test_cases', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_test_cases_last_run_id'), 'agent_test_cases', ['last_run_id'], unique=False)
    op.create_index(op.f('ix_agent_test_cases_last_runtime_plan_hash'), 'agent_test_cases', ['last_runtime_plan_hash'], unique=False)
    op.create_index('ix_agent_test_cases_org_agent_status_created', 'agent_test_cases', ['org_id', 'agent_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_test_cases_org_id'), 'agent_test_cases', ['org_id'], unique=False)
    op.create_table('agent_test_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suite_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('runtime_plan_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('expected_keywords_json', sa.Text(), nullable=False),
    sa.Column('assertion_json', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('assertion_errors_json', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_test_runs_agent_id'), 'agent_test_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_test_runs_agent_run_id'), 'agent_test_runs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_test_runs_case_id'), 'agent_test_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_test_runs_conversation_id'), 'agent_test_runs', ['conversation_id'], unique=False)
    op.create_index('ix_agent_test_runs_org_agent_case_started', 'agent_test_runs', ['org_id', 'agent_id', 'case_id', 'started_at', 'id'], unique=False)
    op.create_index('ix_agent_test_runs_org_agent_hash_case_started', 'agent_test_runs', ['org_id', 'agent_id', 'runtime_plan_hash', 'case_id', 'started_at', 'id'], unique=False)
    op.create_index('ix_agent_test_runs_org_agent_status_case_started', 'agent_test_runs', ['org_id', 'agent_id', 'status', 'case_id', 'started_at', 'id'], unique=False)
    op.create_index(op.f('ix_agent_test_runs_org_id'), 'agent_test_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_test_runs_runtime_plan_hash'), 'agent_test_runs', ['runtime_plan_hash'], unique=False)
    op.create_index(op.f('ix_agent_test_runs_suite_run_id'), 'agent_test_runs', ['suite_run_id'], unique=False)
    op.create_table('agent_test_suite_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('runtime_plan_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_test_suite_runs_agent_id'), 'agent_test_suite_runs', ['agent_id'], unique=False)
    op.create_index('ix_agent_test_suite_runs_org_agent_started', 'agent_test_suite_runs', ['org_id', 'agent_id', 'started_at', 'id'], unique=False)
    op.create_index(op.f('ix_agent_test_suite_runs_org_id'), 'agent_test_suite_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_test_suite_runs_runtime_plan_hash'), 'agent_test_suite_runs', ['runtime_plan_hash'], unique=False)
    op.create_table('agents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tools_json', sa.Text(), nullable=False),
    sa.Column('skills_json', sa.Text(), nullable=False),
    sa.Column('subagents_json', sa.Text(), nullable=False),
    sa.Column('memory_json', sa.Text(), nullable=False),
    sa.Column('filesystem_json', sa.Text(), nullable=False),
    sa.Column('permissions_json', sa.Text(), nullable=False),
    sa.Column('runtime_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('harness_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('model_override_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('routing_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.Text(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("status IN ('unpublished', 'published', 'inactive')", name='ck_agents_status_lifecycle'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_org_id'), 'agents', ['org_id'], unique=False)
    op.create_index('ix_agents_org_id_slug', 'agents', ['org_id', 'slug'], unique=True)
    op.create_index(op.f('ix_agents_slug'), 'agents', ['slug'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_used_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('revoked_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('revoked_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_org_id'), 'api_tokens', ['org_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_revoked_by'), 'api_tokens', ['revoked_by'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_token_type'), 'api_tokens', ['token_type'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_org_id'), 'conversations', ['org_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vector_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_agent_id'), 'knowledge_chunks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_chunk_hash'), 'knowledge_chunks', ['chunk_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_content_hash'), 'knowledge_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_embedding_status'), 'knowledge_chunks', ['embedding_status'], unique=False)
    op.create_index('ix_knowledge_chunks_org_agent', 'knowledge_chunks', ['org_id', 'agent_id'], unique=False)
    op.create_index('ix_knowledge_chunks_org_agent_content_hash', 'knowledge_chunks', ['org_id', 'agent_id', 'content_hash'], unique=False)
    op.create_index('ix_knowledge_chunks_org_document_ordinal', 'knowledge_chunks', ['org_id', 'document_id', 'ordinal'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_org_id'), 'knowledge_chunks', ['org_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_agent_id'), 'knowledge_documents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_org_id'), 'knowledge_documents', ['org_id'], unique=False)
    op.create_table('knowledge_retrieval_audits',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indexed_chunks', sa.Integer(), nullable=False),
    sa.Column('retrieved_chunks', sa.Integer(), nullable=False),
    sa.Column('terms_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_refs_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_retrieval_audits_agent_id'), 'knowledge_retrieval_audits', ['agent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_retrieval_audits_conversation_id'), 'knowledge_retrieval_audits', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_knowledge_retrieval_audits_index_source'), 'knowledge_retrieval_audits', ['index_source'], unique=False)
    op.create_index('ix_knowledge_retrieval_audits_org_agent_created_at', 'knowledge_retrieval_audits', ['org_id', 'agent_id', 'created_at'], unique=False)
    op.create_index('ix_knowledge_retrieval_audits_org_conversation_created_at', 'knowledge_retrieval_audits', ['org_id', 'conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_retrieval_audits_org_id'), 'knowledge_retrieval_audits', ['org_id'], unique=False)
    op.create_index('ix_knowledge_retrieval_audits_org_run_created_at', 'knowledge_retrieval_audits', ['org_id', 'run_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_retrieval_audits_run_id'), 'knowledge_retrieval_audits', ['run_id'], unique=False)
    op.create_index(op.f('ix_knowledge_retrieval_audits_source'), 'knowledge_retrieval_audits', ['source'], unique=False)
    op.create_table('llm_configs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('available_models_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('extra_headers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_check_status', sa.Text(), nullable=False),
    sa.Column('last_check_message', sa.Text(), nullable=False),
    sa.Column('last_checked_at', sa.Text(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_configs_org_id'), 'llm_configs', ['org_id'], unique=False)
    op.create_table('llm_invocation_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('runtime_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subagent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('first_token_ms', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_invocation_logs_agent_id'), 'llm_invocation_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_llm_invocation_logs_conversation_id'), 'llm_invocation_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_llm_invocation_logs_llm_config_id'), 'llm_invocation_logs', ['llm_config_id'], unique=False)
    op.create_index(op.f('ix_llm_invocation_logs_model'), 'llm_invocation_logs', ['model'], unique=False)
    op.create_index('ix_llm_invocation_logs_org_agent_created_at', 'llm_invocation_logs', ['org_id', 'agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_invocation_logs_org_id'), 'llm_invocation_logs', ['org_id'], unique=False)
    op.create_index('ix_llm_invocation_logs_org_provider_created_at', 'llm_invocation_logs', ['org_id', 'provider_type', 'created_at'], unique=False)
    op.create_index('ix_llm_invocation_logs_org_run_created_at', 'llm_invocation_logs', ['org_id', 'run_id', 'created_at'], unique=False)
    op.create_index('ix_llm_invocation_logs_org_scope_created_at', 'llm_invocation_logs', ['org_id', 'runtime_scope', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_invocation_logs_provider_type'), 'llm_invocation_logs', ['provider_type'], unique=False)
    op.create_index(op.f('ix_llm_invocation_logs_run_id'), 'llm_invocation_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_llm_invocation_logs_runtime_scope'), 'llm_invocation_logs', ['runtime_scope'], unique=False)
    op.create_index(op.f('ix_llm_invocation_logs_source'), 'llm_invocation_logs', ['source'], unique=False)
    op.create_index(op.f('ix_llm_invocation_logs_status'), 'llm_invocation_logs', ['status'], unique=False)
    op.create_index(op.f('ix_llm_invocation_logs_subagent_name'), 'llm_invocation_logs', ['subagent_name'], unique=False)
    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_org_id'), 'messages', ['org_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_org_id'), 'organization_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('run_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_seq', sa.Integer(), nullable=True),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subagent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('input_preview', sa.Text(), nullable=False),
    sa.Column('output_preview', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_run_events_run_seq')
    )
    op.create_index(op.f('ix_run_events_agent_id'), 'run_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_run_events_call_id'), 'run_events', ['call_id'], unique=False)
    op.create_index('ix_run_events_org_agent_created', 'run_events', ['org_id', 'agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_run_events_org_id'), 'run_events', ['org_id'], unique=False)
    op.create_index('ix_run_events_org_run_seq', 'run_events', ['org_id', 'run_id', 'seq'], unique=False)
    op.create_index('ix_run_events_org_type_created', 'run_events', ['org_id', 'type', 'created_at'], unique=False)
    op.create_index(op.f('ix_run_events_phase'), 'run_events', ['phase'], unique=False)
    op.create_index(op.f('ix_run_events_resource'), 'run_events', ['resource'], unique=False)
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_events_seq'), 'run_events', ['seq'], unique=False)
    op.create_index(op.f('ix_run_events_status'), 'run_events', ['status'], unique=False)
    op.create_index(op.f('ix_run_events_step_id'), 'run_events', ['step_id'], unique=False)
    op.create_index(op.f('ix_run_events_subagent'), 'run_events', ['subagent'], unique=False)
    op.create_index(op.f('ix_run_events_type'), 'run_events', ['type'], unique=False)
    op.create_table('skill_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed_tools_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_versions_name'), 'skill_versions', ['name'], unique=False)
    op.create_index(op.f('ix_skill_versions_org_id'), 'skill_versions', ['org_id'], unique=False)
    op.create_index(op.f('ix_skill_versions_skill_id'), 'skill_versions', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_versions_version'), 'skill_versions', ['version'], unique=False)
    op.create_table('skills',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed_tools_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_index(op.f('ix_skills_org_id'), 'skills', ['org_id'], unique=False)
    op.create_table('tool_definitions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('implementation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_definitions_org_id'), 'tool_definitions', ['org_id'], unique=False)
    op.create_table('tool_invocation_audits',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('implementation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_invocation_audits_agent_id'), 'tool_invocation_audits', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_invocation_audits_call_id'), 'tool_invocation_audits', ['call_id'], unique=False)
    op.create_index(op.f('ix_tool_invocation_audits_conversation_id'), 'tool_invocation_audits', ['conversation_id'], unique=False)
    op.create_index('ix_tool_invocation_audits_org_conversation_created_at', 'tool_invocation_audits', ['org_id', 'conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tool_invocation_audits_org_id'), 'tool_invocation_audits', ['org_id'], unique=False)
    op.create_index('ix_tool_invocation_audits_org_run_created_at', 'tool_invocation_audits', ['org_id', 'run_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tool_invocation_audits_run_id'), 'tool_invocation_audits', ['run_id'], unique=False)
    op.create_index(op.f('ix_tool_invocation_audits_tool_id'), 'tool_invocation_audits', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_invocation_audits_user_id'), 'tool_invocation_audits', ['user_id'], unique=False)
    op.create_table('tool_secrets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_secrets_org_id'), 'tool_secrets', ['org_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_conversation_id'), 'uploads', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_uploads_org_id'), 'uploads', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_login_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_uploads_org_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_conversation_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_tool_secrets_org_id'), table_name='tool_secrets')
    op.drop_table('tool_secrets')
    op.drop_index(op.f('ix_tool_invocation_audits_user_id'), table_name='tool_invocation_audits')
    op.drop_index(op.f('ix_tool_invocation_audits_tool_id'), table_name='tool_invocation_audits')
    op.drop_index(op.f('ix_tool_invocation_audits_run_id'), table_name='tool_invocation_audits')
    op.drop_index('ix_tool_invocation_audits_org_run_created_at', table_name='tool_invocation_audits')
    op.drop_index(op.f('ix_tool_invocation_audits_org_id'), table_name='tool_invocation_audits')
    op.drop_index('ix_tool_invocation_audits_org_conversation_created_at', table_name='tool_invocation_audits')
    op.drop_index(op.f('ix_tool_invocation_audits_conversation_id'), table_name='tool_invocation_audits')
    op.drop_index(op.f('ix_tool_invocation_audits_call_id'), table_name='tool_invocation_audits')
    op.drop_index(op.f('ix_tool_invocation_audits_agent_id'), table_name='tool_invocation_audits')
    op.drop_table('tool_invocation_audits')
    op.drop_index(op.f('ix_tool_definitions_org_id'), table_name='tool_definitions')
    op.drop_table('tool_definitions')
    op.drop_index(op.f('ix_skills_org_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_skill_versions_version'), table_name='skill_versions')
    op.drop_index(op.f('ix_skill_versions_skill_id'), table_name='skill_versions')
    op.drop_index(op.f('ix_skill_versions_org_id'), table_name='skill_versions')
    op.drop_index(op.f('ix_skill_versions_name'), table_name='skill_versions')
    op.drop_table('skill_versions')
    op.drop_index(op.f('ix_run_events_type'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_subagent'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_step_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_status'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_seq'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_resource'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_phase'), table_name='run_events')
    op.drop_index('ix_run_events_org_type_created', table_name='run_events')
    op.drop_index('ix_run_events_org_run_seq', table_name='run_events')
    op.drop_index(op.f('ix_run_events_org_id'), table_name='run_events')
    op.drop_index('ix_run_events_org_agent_created', table_name='run_events')
    op.drop_index(op.f('ix_run_events_call_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_agent_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_org_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_messages_org_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_llm_invocation_logs_subagent_name'), table_name='llm_invocation_logs')
    op.drop_index(op.f('ix_llm_invocation_logs_status'), table_name='llm_invocation_logs')
    op.drop_index(op.f('ix_llm_invocation_logs_source'), table_name='llm_invocation_logs')
    op.drop_index(op.f('ix_llm_invocation_logs_runtime_scope'), table_name='llm_invocation_logs')
    op.drop_index(op.f('ix_llm_invocation_logs_run_id'), table_name='llm_invocation_logs')
    op.drop_index(op.f('ix_llm_invocation_logs_provider_type'), table_name='llm_invocation_logs')
    op.drop_index('ix_llm_invocation_logs_org_scope_created_at', table_name='llm_invocation_logs')
    op.drop_index('ix_llm_invocation_logs_org_run_created_at', table_name='llm_invocation_logs')
    op.drop_index('ix_llm_invocation_logs_org_provider_created_at', table_name='llm_invocation_logs')
    op.drop_index(op.f('ix_llm_invocation_logs_org_id'), table_name='llm_invocation_logs')
    op.drop_index('ix_llm_invocation_logs_org_agent_created_at', table_name='llm_invocation_logs')
    op.drop_index(op.f('ix_llm_invocation_logs_model'), table_name='llm_invocation_logs')
    op.drop_index(op.f('ix_llm_invocation_logs_llm_config_id'), table_name='llm_invocation_logs')
    op.drop_index(op.f('ix_llm_invocation_logs_conversation_id'), table_name='llm_invocation_logs')
    op.drop_index(op.f('ix_llm_invocation_logs_agent_id'), table_name='llm_invocation_logs')
    op.drop_table('llm_invocation_logs')
    op.drop_index(op.f('ix_llm_configs_org_id'), table_name='llm_configs')
    op.drop_table('llm_configs')
    op.drop_index(op.f('ix_knowledge_retrieval_audits_source'), table_name='knowledge_retrieval_audits')
    op.drop_index(op.f('ix_knowledge_retrieval_audits_run_id'), table_name='knowledge_retrieval_audits')
    op.drop_index('ix_knowledge_retrieval_audits_org_run_created_at', table_name='knowledge_retrieval_audits')
    op.drop_index(op.f('ix_knowledge_retrieval_audits_org_id'), table_name='knowledge_retrieval_audits')
    op.drop_index('ix_knowledge_retrieval_audits_org_conversation_created_at', table_name='knowledge_retrieval_audits')
    op.drop_index('ix_knowledge_retrieval_audits_org_agent_created_at', table_name='knowledge_retrieval_audits')
    op.drop_index(op.f('ix_knowledge_retrieval_audits_index_source'), table_name='knowledge_retrieval_audits')
    op.drop_index(op.f('ix_knowledge_retrieval_audits_conversation_id'), table_name='knowledge_retrieval_audits')
    op.drop_index(op.f('ix_knowledge_retrieval_audits_agent_id'), table_name='knowledge_retrieval_audits')
    op.drop_table('knowledge_retrieval_audits')
    op.drop_index(op.f('ix_knowledge_documents_org_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_agent_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_knowledge_chunks_org_id'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_org_document_ordinal', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_org_agent_content_hash', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_org_agent', table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_embedding_status'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_content_hash'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_chunk_hash'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_agent_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_conversations_org_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_type'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_revoked_by'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_org_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_agents_slug'), table_name='agents')
    op.drop_index('ix_agents_org_id_slug', table_name='agents')
    op.drop_index(op.f('ix_agents_org_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_agent_test_suite_runs_runtime_plan_hash'), table_name='agent_test_suite_runs')
    op.drop_index(op.f('ix_agent_test_suite_runs_org_id'), table_name='agent_test_suite_runs')
    op.drop_index('ix_agent_test_suite_runs_org_agent_started', table_name='agent_test_suite_runs')
    op.drop_index(op.f('ix_agent_test_suite_runs_agent_id'), table_name='agent_test_suite_runs')
    op.drop_table('agent_test_suite_runs')
    op.drop_index(op.f('ix_agent_test_runs_suite_run_id'), table_name='agent_test_runs')
    op.drop_index(op.f('ix_agent_test_runs_runtime_plan_hash'), table_name='agent_test_runs')
    op.drop_index(op.f('ix_agent_test_runs_org_id'), table_name='agent_test_runs')
    op.drop_index('ix_agent_test_runs_org_agent_status_case_started', table_name='agent_test_runs')
    op.drop_index('ix_agent_test_runs_org_agent_hash_case_started', table_name='agent_test_runs')
    op.drop_index('ix_agent_test_runs_org_agent_case_started', table_name='agent_test_runs')
    op.drop_index(op.f('ix_agent_test_runs_conversation_id'), table_name='agent_test_runs')
    op.drop_index(op.f('ix_agent_test_runs_case_id'), table_name='agent_test_runs')
    op.drop_index(op.f('ix_agent_test_runs_agent_run_id'), table_name='agent_test_runs')
    op.drop_index(op.f('ix_agent_test_runs_agent_id'), table_name='agent_test_runs')
    op.drop_table('agent_test_runs')
    op.drop_index(op.f('ix_agent_test_cases_org_id'), table_name='agent_test_cases')
    op.drop_index('ix_agent_test_cases_org_agent_status_created', table_name='agent_test_cases')
    op.drop_index(op.f('ix_agent_test_cases_last_runtime_plan_hash'), table_name='agent_test_cases')
    op.drop_index(op.f('ix_agent_test_cases_last_run_id'), table_name='agent_test_cases')
    op.drop_index(op.f('ix_agent_test_cases_agent_id'), table_name='agent_test_cases')
    op.drop_table('agent_test_cases')
    op.drop_index('ix_agent_runs_total_tokens', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_spec_hash'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_runtime_source'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_run_source'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_rerun_of_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_release_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_org_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_entrypoint'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_release_snapshots_version'), table_name='agent_release_snapshots')
    op.drop_index(op.f('ix_agent_release_snapshots_spec_hash'), table_name='agent_release_snapshots')
    op.drop_index(op.f('ix_agent_release_snapshots_org_id'), table_name='agent_release_snapshots')
    op.drop_index(op.f('ix_agent_release_snapshots_manifest_hash'), table_name='agent_release_snapshots')
    op.drop_index(op.f('ix_agent_release_snapshots_agent_id'), table_name='agent_release_snapshots')
    op.drop_table('agent_release_snapshots')
    # ### end Alembic commands ###
